### ISSUE TITLE
پیام pin

### ISSUE THREAD

**Issue by shabda7** [sir-kokabi/twifiner#1]
سلام. پیام‌های pin در توئیتر سفید نمایش داده می‌شود. فقط همین پیام اول. 
![photo_2024-02-02_23-58-30](https://github.com/sir-kokabi/twifiner/assets/127131184/9044d6f9-507b-4cd7-9de1-f253acd15a29)

**Comment by sir-kokabi** [comment]
سلام آقا وحید.
ممنون بابت گزارش این مشکل.
اینقدر تعداد فیچرها و چالشها زیاد بود که کلا تم دارک رو یادم رفته. 🤦
احتمالا برای mutual friendsها هم همین مشکل وجود داشته باشه.
فعلا تا زمان حال مشکل چاره‌ای جز استفاده از تم لایت نیست.
من این رو در اولویت بررسی قرار میدم چون خیلی مهمه.

**Comment by shabda7** [comment]
ببخشید بابت سوتفاهم پیش اومده. من آقا وحید نیستم. دنبال‌کننده‌ی ایشون هستم. اسکرین‌شات رو از صفحه‌ی ایشون گرفتم فقط. به غیر از این مسئله‌ی پیام سنجاق‌شده،‌ بقیه‌ی مسائل خیلی خوب کار می‌کنه. ممنون برای کار خوبتون.

**Comment by sir-kokabi** [comment]
خواهش می‌کنم.
سلامت باشید. 🙏
