### ISSUE TITLE
Issues with Installing package.json and Watcher

### ISSUE THREAD

**Issue by Amm1rr** [sir-kokabi/twifiner#2]
Hi!
I'm a bit confused while setting up the development environment. When installing `package.json`, numerous errors are occurring.
The log is quite confusing; perhaps it's specific to my system.

**UPDATE:**
Well, I still can't build the project, but I guess the issue lies in the installation of [Watcher](https://github.com/parcel-bundler/watcher/issues/156) package

**Comment by ayub-kokabi** [comment]
Hi @Amm1rr 
Thank you for your interest in contributing to this project. 
twifiner is developed using the [Plasmo framework](https://docs.plasmo.com/). 
I've added a [contributing](https://github.com/sir-kokabi/twifiner#contributing) section to the readme. 
Follow the instructions there to begin developing the project

**Comment by Amm1rr** [comment]
Thanks Ayoub,

I've been trying hard, but I've run into a snag while installing Plasmo. The specific issue is with the message: 

```bash
npm ERR! gyp: binding.gyp not found (cwd: /home/amir/Works/twifiner/node_modules/@parcel/watcher) while trying to load binding.gyp
```

I'm currently in the process of troubleshooting to pinpoint the problem. I'll keep you posted on my findings.

**Comment by Amm1rr** [comment]
Thanks Ayoub,
I've been trying hard, but I've run into a snag while installing Plasmo. The specific issue is with the message: 

```bash
npm ERR! gyp: binding.gyp not found (cwd: /home/amir/Works/twifiner/node_modules/@parcel/watcher) while trying to load binding.gyp
```

I'm currently in the process of troubleshooting to pinpoint the problem. I'll keep you posted on my findings.

Just a question, What version of Python do you have installed?

**Comment by Amm1rr** [comment]
Well, I used [below command](https://github.com/parcel-bundler/parcel/issues/8152#issuecomment-1836317858) to install and it's worked!

```
npm install -D --ignore-scripts
npm install -D plasmo --ignore-scripts
npm install -D sharp --ignore-scripts
```

**Comment by ayub-kokabi** [comment]
Hey Amir,
I'm a bit concerned that you're using a non-standard method to install the required packages. 😉
Consider using pnpm, as suggested in the official docs. It might resolve the issues!
![image](https://github.com/sir-kokabi/twifiner/assets/116794136/0d26efd4-8281-47a4-8470-77fb8f8106bb)

**Comment by Amm1rr** [comment]
🫠
I have tried using **pnpm** before, but it resulted in an error. Now, I have tried again, and it is working successfully.

`pnpm install`

Thanks buddy

**Comment by ayub-kokabi** [comment]
Good news!
Since everything is working now, I close this issue. 
Thanks for the update!
